# ansible/playbooks/argocd-setup.yml
---
- name: Bootstrap Argo CD Layer
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    repo_url: 'https://github.com/23hp/immutable-gate-apps.git'
  roles:
    - role: argocd
