[podman_host]
# config ~/.ssh/config to have the Host podman 
podman ansible_python_interpreter=/usr/bin/python3

[server_host]
# config ~/.ssh/config to have the Host server 
server ansible_python_interpreter=/usr/bin/python3