---
- name: Setup Talos Linux
  hosts: localhost
  gather_facts: false
  roles:
    - talos
    - argocd
  vars:
    talos_tasks:
      - activate.yml
      # - patch.yml
    # talos_patches: []
    repo_url: 'https://github.com/23hp/immutable-gate-apps.git'
