---
- name: Setup Talos Linux
  hosts: localhost
  gather_facts: false
  roles:
    - talos
  vars:
    talos_tasks:
      # - reset.yml
      # - destroy.yml
      - activate.yml
    talos_patches: []
