- name: Home Server Stack (Rootless Podman)
  hosts: homelab
  vars:
    my_apps:
      - traefik
      - adguardhome
  tasks:
    - name: Setup Podman environment
      ansible.builtin.include_role:
        name: setup
      tags: ['setup']

    - name: Remove all quadlets (use with caution)
      tags: ['cleanup']
      containers.podman.podman_quadlet:
        state: absent
        all: true

    - name: Deploy Applications
      tags: ['apps']
      ansible.builtin.include_role:
        name: apps
      vars:
        apps_name: "{{ app_to_deploy }}"
      loop: "{{ my_apps }}"
      loop_control:
        loop_var: app_to_deploy