- name: Infrastructure Base Layer (Root)
  hosts: server_host
  tags: ['infra']
  roles:
    - infra
- name: Home Server Stack (Rootless Podman)
  hosts: podman_host
  tags: ['podman']
  vars:
    ansible_env:
      XDG_RUNTIME_DIR: "/run/user/{{ ansible_effective_user_id }}"
  roles:
    - role: podman
      tags: ['podman']
    - role: technitium
      tags: ['dns']
    - role: traefik
      tags: ['reverse_proxy']
    - role: immich
