# ansible/playbooks/system-operate.yml
---
- name: Setup Talos Linux
  hosts: localhost
  gather_facts: false
  roles:
    - talos
  vars:
    talos_tasks:
      - install.yml
      # - reset.yml
      # - activate.yml
      # - gen_config.yml
    talos_patches: []
