http:
  serversTransports:
    ignore-ssl:
      insecureSkipVerify: true
  routers:
    router:
      # insecureSkipVerify: true
      rule: 'Host(`router.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "router-svc"
    wifi:
      # insecureSkipVerify: true
      rule: 'Host(`wifi.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "wifi-svc"
    proxmox:
      rule: 'Host(`proxmox.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "proxmox-svc"
    dns:
      rule: 'Host(`dns.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "dns-svc"
  services:
    router-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.10.1"
    wifi-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.10.2"
    proxmox-svc:
      loadBalancer:
        serversTransport: ignore-ssl
        servers:
          - url: "https://192.168.10.3:8006"
    dns-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.10.4:5380"