http:
  routers:
    router:
      tls: # Wildcard Domain: apply once, use everywhere
        domains:
          - main: "{{ env `DOMAIN_NAME` }}"
            sans: [ "*.{{ env `DOMAIN_NAME` }}" ]
      # insecureSkipVerify: true
      rule: 'Host(`router.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "router-svc"
    wifi:
      # insecureSkipVerify: true
      rule: 'Host(`wifi.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "wifi-svc"
    proxmox:
      # insecureSkipVerify: true
      rule: 'Host(`proxmox.{{ env "DOMAIN_NAME" }}`)'
      entryPoints: ["websecure"]
      service: "proxmox-svc"

  services:
    router-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1"
    wifi-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2"
    proxmox-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.1.3"
            port: 8006