services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    environment:
      - LT_LOAD_ONLY=en,zh,de # zh-Hans
      - LT_UPDATE_MODELS=true
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 10s
      timeout: 4s
      retries: 4
      start_period: 5s
    volumes:
      - lt-local:/home/libretranslate/.local
    networks:
      - traefik-public

volumes:
  lt-local:

networks:
  traefik-public:
    external: true