---
- name: "Deploy configuration files (Template-based) - {{ apps_name }}"
  ansible.builtin.template:
    src: "{{ role_path }}/{{ apps_name }}/config.yaml.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.config/{{ apps_name }}/AdGuardHome.yaml"
    mode: '0600'
  notify: "Restart app"
  no_log: true

- name: "Copy Quadlet files - {{ apps_name }}"
  ansible.builtin.template:
    src: "{{ role_path }}/{{ apps_name }}/{{ apps_name }}.container.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.config/containers/systemd/{{ apps_name }}.container"
    mode: '600'
  notify: "Restart app"

- name: "Copy Quadlet files - {{ apps_name }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/{{ apps_name }}/{{ item }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/containers/systemd/"
    mode: '600'
  notify: "Restart app"
  loop:
    - "{{ apps_name }}.volume"
