# roles/apps/tasks/main.yml
- name: Update tracking fact for rescue block
  ansible.builtin.set_fact:
    # set var global visible including rescue
    apps_last_attempted_app: "{{ apps_name }}"

- name: "Ensure config and quadlet directories exist"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/{{ apps_name }}"
    state: directory
    mode: '0700'

- name: "Load custom deployment task"
  ansible.builtin.include_tasks: "{{ apps_name }}.yml"

- name: "Apply changes immediately"
  ansible.builtin.meta: flush_handlers

- name: "Ensure running"
  ansible.builtin.systemd:
    name: "{{ apps_name }}.service"
    scope: user
    state: started
