# roles/infra/tasks/main.yml
- name: Create VLAN {{ infra_vlan_id }}
  community.general.nmcli:
    conn_name: "VLAN-{{ infra_vlan_id }}-Connection"
    ifname: "{{ infra_physical_iface }}.{{ infra_vlan_id }}"
    type: vlan
    vlanid: "{{ infra_vlan_id }}"
    vlandev: "{{ infra_physical_iface }}"
    state: present
    autoconnect: true

- name: Create podman user
  ansible.builtin.user:
    name: podman
    shell: /bin/bash
    create_home: true
    state: present
- name: Set authorized key for podman user
  ansible.posix.authorized_key:
    user: podman
    state: present
    key: "{{ lookup('file', infra_homelab_public_key) }}"
- name: Ensure user linger is enabled for rootless containers
  ansible.builtin.command: "loginctl enable-linger podman"
  args:
    creates: "/var/lib/systemd/linger/podman"
- name: Configure subuid/subgid for Rootless mode
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "podman:100000:65536"
    create: true
    mode: '0644'
  loop:
    - /etc/subuid
    - /etc/subgid

- name: Configure Registry Mirrors
  ansible.builtin.copy:
    dest: /etc/containers/registries.conf
    content: |
      unqualified-search-registries = ["docker.io", "quay.io"]
    mode: '0644'
