services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - cloudflare_api_token
    env_file:
      - "../.env"
    volumes:
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock:ro"
      - "./certs:/letsencrypt"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic:/etc/traefik/dynamic:ro"
#    labels:
#      - "traefik.enable=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

networks:
  traefik-public:
    external: true

secrets:
  cloudflare_api_token:
    file: ../secrets/cloudflare_api_token.txt
