# Traefik static config: https://doc.traefik.io/traefik/reference/static-configuration/file/ 
# supported nodes: global, serversTransport, entryPoints, providers, api, metrics, tracing, hostResolver, certificatesResolvers
# User environment variables to set confidential information

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - "security-headers@file"
      tls: 
        certResolver: letsencrypt

providers:
  file: # monitor dynamic configuration changes in this directory
    directory: /etc/traefik/dynamic
    watch: true
  docker:
    exposedByDefault: false

ping: {} # Healthcheck

api:
  # Dashboard
  dashboard: true
  insecure: true
log:
  level: INFO # default level: ERROR

certificatesresolvers:
  letsencrypt:
    acme:
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        resolvers:
            - "1.1.1.1:53"
        provider: cloudflare