---
- name: Ensure TFTP root directory exists
  ansible.builtin.file:
    path: "{{ router_tftp_root }}"
    state: directory
    mode: '0755'

- name: Check TFTP Port
  ansible.builtin.shell: "netstat -lutnp | grep ':69 '"
  register: port_result
  failed_when: false
  changed_when: false

- name: Start dnsmasq manually if not running
  ansible.builtin.command:
    dnsmasq --port=0 --enable-tftp --tftp-root={{ router_tftp_root }}
  when: port_result.stdout == ""
