---
- name: Upload file to Memory
  ansible.builtin.template:
    src: "{{ httpserver_file_src }}"
    dest: "/tmp/{{ httpserver_file_relative_path }}"
    mode: "0644"

- name: Create symbolic link in Web root
  ansible.builtin.file:
    src: /tmp/{{ httpserver_file_relative_path }}
    dest: "{{ httpserver_web_root }}/{{ httpserver_file_relative_path }}"
    state: link
    force: true
